# -*- coding: utf-8 -*-
"""Merging_Different_Timetypes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_1Za36ZVnv73wqV58miSpVwNCcbcgI2q
"""

import pandas as pd
stb_14=pd.read_excel('F:\\Jio\\Design\\phase2\\3-Jun-Format\\stb_14.xlsx')
stb_14

stb_14_1=stb_14[['di8','dt','as7','as5','name','mi1']]
stb_14_1

import datetime

datetime_object = datetime.datetime.strptime(str(stb_14_1['dt'][0]),'%Y-%d-%m %H:%M:%S')
datetime_output = datetime_object.strftime('%Y/%m/%d %H:%M:%S')
datetime_output

for i in range(len(stb_14_1)):
  datetime_object = datetime.datetime.strptime(str(stb_14_1['dt'][i]),'%Y-%d-%m %H:%M:%S')
  datetime_output = datetime_object.strftime('%Y/%m/%d %H:%M:%S')
  stb_14_1['dt'][i]=datetime_output

stb_27=pd.read_excel('F:\\Jio\\Design\\phase2\\3-Jun-Format\\stb_27.xlsx')
stb_27

stb_27.columns = stb_27.columns.str.replace(' ', '')
stb_27.columns

stb_27_1=stb_27[['di8','date1','as7','name','as5','mi1']]
stb_27_1

datetime_object = datetime.datetime.strptime(str(stb_27_1['date1'][0]).strip(),'%Y-%m-%d %H:%M:%S')
datetime_output = datetime_object.strftime('%Y/%m/%d %H:%M:%S')
datetime_output

for i in range(len(stb_27_1)):
  datetime_object = datetime.datetime.strptime(str(stb_27_1['date1'][i]).strip(),'%Y-%m-%d %H:%M:%S')
  datetime_output = datetime_object.strftime('%Y/%m/%d %H:%M:%S')
  stb_27_1['date1'][i]=datetime_output

stb_32=pd.read_excel('F:\\Jio\\Design\\phase2\\3-Jun-Format\\stb_32.xlsx')
stb_32

stb_32.columns = stb_32.columns.str.lstrip()
stb_32.columns = stb_32.columns.str.rstrip()
stb_32.columns

stb_32_1=stb_32[['di8','dt1','as7','name','as5','mi1']]
stb_32_1

datetime_object = datetime.datetime.strptime(str(stb_32_1['dt1'][0]).strip(),'%Y-%m-%d %H:%M:%S')
datetime_output = datetime_object.strftime('%Y/%m/%d %H:%M:%S')
datetime_output

for i in range(len(stb_32_1)):
  datetime_object = datetime.datetime.strptime(str(stb_32_1['dt1'][i]).strip(),'%Y-%m-%d %H:%M:%S')
  datetime_output = datetime_object.strftime('%Y/%m/%d %H:%M:%S')
  stb_32_1['dt1'][i]=datetime_output

stb_27_1=stb_27_1.rename(columns={"date1": "dt"})
stb_32_1=stb_32_1.rename(columns={"dt1": "dt"})

stb = [stb_14_1, stb_27_1, stb_32_1]
result = pd.concat(stb)
result

result.to_csv('final_stb_data.csv')